# Generated by Django 4.2.13 on 2024-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_player_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('I', 'IN_GAME')], default='O', max_length=1),
        ),
    ]
