# Generated by Django 4.2.13 on 2024-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_remove_player_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alias',
            field=models.CharField(default='dummy', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE')], default='F', max_length=1),
        ),
    ]
