# Generated by Django 4.2.13 on 2024-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_player_alias_alter_player_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='alias',
        ),
    ]
