# Generated by Django 4.2.13 on 2024-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_remove_player_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE')], default='O', max_length=1),
        ),
    ]
