# Generated by Django 4.2.13 on 2024-06-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('I', 'INGAME')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_01_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAME01', to='online.gamehistory')),
                ('game_02_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAME02', to='online.gamehistory')),
                ('game_final_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAMEFINAL', to='online.gamehistory')),
            ],
        ),
    ]
