# Generated by Django 4.2.13 on 2024-06-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_alter_player_status_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='online.player'),
            preserve_default=False,
        ),
    ]
