global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/alertmanager/rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]

remote_write:
  - url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
    basic_auth:
      username: 1437461
      password: ${ALERT_PASS}
