version: "3.8"

services:
  PostgreSQL:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080