# Generated by Django 4.2.11 on 2024-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0002_remove_achievement_xp_achievement_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
