# Generated by Django 4.2.11 on 2024-05-04 17:21

from django.db import migrations, models
import userman.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0005_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='http://127.0.0.1:2500/media/store/images/Photo_on_5-2-24_at_4.57_PM.jpg', upload_to='store/images', validators=[userman.validators.max_size_validator]),
        ),
    ]
