import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import FriendBar from "./_components/friendBar";
import SideBar from "./_components/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}){
  return (
    <html lang="en">
      <body className={cn(`bg-background text-foreground text-sm flex`, inter.className)} >
        <SideBar/>
        <div className="flex flex-col [&>*]:h-full  max-w-[2560px] mx-auto max-h-[120rem] flex-1 ">
        {children}
        </div>
        <FriendBar />
        </body>
    </html>
  );
}
