# Generated by Django 4.2.11 on 2024-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='xp',
        ),
        migrations.AddField(
            model_name='achievement',
            name='desc',
            field=models.CharField(default='hehe boi', max_length=256),
            preserve_default=False,
        ),
    ]
