# Generated by Django 4.2.11 on 2024-05-04 16:34

from django.db import migrations, models
import userman.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0004_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='null', upload_to='store/images', validators=[userman.validators.max_size_validator]),
        ),
    ]
