# Generated by Django 4.2.11 on 2024-05-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0007_alter_player_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
