# Generated by Django 4.2.11 on 2024-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0008_alter_friendshiprequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=10),
        ),
    ]
