# Generated by Django 4.2.11 on 2024-05-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0008_alter_friendshiprequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementperuser',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.achievement'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player1', 'player2')},
        ),
    ]
