# Generated by Django 4.2.11 on 2024-05-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0009_alter_achievementperuser_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementperuser',
            old_name='item',
            new_name='achievement',
        ),
    ]
