# Generated by Django 4.2.11 on 2024-05-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0010_rename_item_achievementperuser_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementperuser',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.achievement', unique=True),
        ),
        migrations.AlterField(
            model_name='itemsperuser',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.item', unique=True),
        ),
    ]
