# Generated by Django 4.2.11 on 2024-05-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0012_alter_achievementperuser_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementperuser',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.achievement'),
        ),
        migrations.AlterField(
            model_name='itemsperuser',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.item'),
        ),
    ]
