# Generated by Django 4.2.11 on 2024-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0012_alter_achievementperuser_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('G', 'IN_GAME')], default='F', max_length=1),
        ),
    ]
