# Generated by Django 4.2.11 on 2024-06-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0013_alter_achievementperuser_achievement_and_more'),
        ('userman', '0013_alter_player_status'),
    ]

    operations = [
    ]
