# Generated by Django 4.2.11 on 2024-06-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0016_alter_invites_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invites',
            unique_together=set(),
        ),
    ]
