# Generated by Django 4.2.11 on 2024-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0017_alter_invites_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
