# Generated by Django 4.2.11 on 2024-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0019_alter_achievement_path_alter_achievement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
