# Generated by Django 4.2.11 on 2024-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0020_alter_item_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_type',
            field=models.CharField(choices=[('O', 'ONLINE'), ('F', 'OFFLINE'), ('G', 'IN_GAME')], default='N', max_length=1),
        ),
    ]
