# Generated by Django 4.2.11 on 2024-07-08 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0021_player_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_01_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAME01', to='userman.gamehistory')),
                ('game_02_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAME02', to='userman.gamehistory')),
                ('game_final_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAMEFINAL', to='userman.gamehistory')),
            ],
        ),
    ]
