# Generated by Django 4.2.11 on 2024-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0022_gamehistory_winner_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('E', 'REJECTED')], default='P', max_length=1),
        ),
    ]
