# Generated by Django 4.2.11 on 2024-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0023_alter_invites_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Q', 'QUEUE'), ('S', 'STARTED')], default='Q', max_length=255)),
                ('players', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
