# Generated by Django 4.2.11 on 2024-07-11 17:41

from django.db import migrations, models
import userman.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0023_alter_invites_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default.png', upload_to='', validators=[userman.validators.max_size_validator]),
        ),
    ]
