# Generated by Django 4.2.11 on 2024-07-11 21:13

from django.db import migrations, models
import userman.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0025_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images', validators=[userman.validators.max_size_validator]),
        ),
    ]
