# Generated by Django 4.2.11 on 2024-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0027_alter_player_status_alter_player_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_42',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
