# Generated by Django 4.2.11 on 2024-07-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0029_tnrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ball',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='userman.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='paddle',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='paddle', to='userman.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='table',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='table', to='userman.item'),
        ),
    ]
