# Generated by Django 4.2.11 on 2024-07-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0029_tnrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image_42',
        ),
    ]
