# Generated by Django 4.2.11 on 2024-07-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0030_player_ball_player_paddle_player_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image_42',
        ),
    ]
