# Generated by Django 4.2.11 on 2024-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0031_remove_player_image_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='327fa8', max_length=6),
        ),
    ]
