# Generated by Django 4.2.11 on 2024-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_alter_player_ball_alter_player_paddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='#327fa8', max_length=7),
        ),
    ]
