# Generated by Django 4.2.11 on 2024-03-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_order_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
