# Generated by Django 4.2.11 on 2024-04-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=models.CharField(default='fname', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='lname', max_length=32),
            preserve_default=False,
        ),
    ]
