# Generated by Django 4.2.11 on 2024-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_firstname_player_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'PENDING'), ('P', 'ACCEPTED'), ('G', 'REJECTED'), ('A', 'REJECTED')], max_length=1)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
    ]
