# Generated by Django 4.2.11 on 2024-04-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opponent_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('game_mode', models.CharField(max_length=64)),
                ('game_duration_minutes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_games', to='players.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player', to='players.player')),
            ],
        ),
    ]
