version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=trans-cluster
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
    env_file:
      - .env
    volumes:
      - esdata:/usr/share/elasticsearch/data
      # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana
    environment:
      - node.name=kibana
      - cluster.name=trans-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - 5601:5601
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - elastic
    restart: on-failure

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.9.1
  #   container_name: logstash
  #   volumes:
  #     - ./logstash/config:/usr/share/logstash/config
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5044:5044
  #   networks:
  #     - elastic
  #   restart: on-failure

volumes:
  esdata:

networks:
  elastic:
    driver: bridge
