{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "REDIS CACHE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "command": "info",
     "section": "clients",
     "streamingCapacity": 1000,
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "command": "info",
     "section": "memory",
     "streamingCapacity": 1000,
     "streamingDataType": "TimeSeries",
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "streamingCapacity": 1, "type": "command" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "type": "command" }
   ]
  },
  {
   "title": "Number of Keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "query": "dbsize", "streamingCapacity": 1000, "streamingInterval": 1000, "type": "cli" }
   ]
  },
  {
   "title": "Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "command": "info",
     "section": "stats",
     "streamingCapacity": 1000,
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  },
  { "title": "DOCKER ENGINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "process_start_time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B - $A)/3600", "type": "math" }
   ]
  },
  {
   "title": "engine_daemon_engine_info",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=\"docker_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_daemon_container_states_containers",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker_exporter\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Alert panel", "type": "alertlist", "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 } },
  {
   "title": "engine_daemon_events_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "engine_daemon_events_total{job=\"docker_exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "engine_daemon_engine_memory_bytes",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{job=\"docker_exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "builder_builds_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "builder_builds_failed_total{job=\"docker_exporter\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}