import { useState } from "react";
import toast from "react-hot-toast";
import AuthCode from "react-auth-code-input";
import axios from "axios";
import { useRecoilValue } from "recoil";
import Url from "../../Atoms/Url";
import { setAuthToken } from "../Utils/setAuthToken";
import { useNavigate } from "react-router-dom";

function Verify2FA2() {
  const [result, setResult] = useState("");
  const url = useRecoilValue(Url);
  const navigate = useNavigate();
  console.log(window.location.search);

  const handleOnChange = (res: string) => {
    setResult(res);
  };

  const obj = {
    code: result,
    user_id: window.location.search.split("=")[1],
  };
  console.log(obj);
  
  const CheckTwoFa = () => {
    axios
      .post(url + "discord/2fa/", obj)
      .then((response) => {
        var str = response.data;
        console.log("verify2: " + JSON.stringify(response));
        if (response.status === 200) {
          toast.success("Logged in successfully");
          localStorage.setItem("token", str.access);
          setAuthToken();
          console.log(str.access);
          navigate("/");
        }
        // window.location.href = response.data?.rediect;
      })
      .catch((error) => {
        console.log("error 2fa222 discord: " + error);
        toast.error(error.response.data.error);
      });
  };

  const show2FA: boolean = result.length === 6 ? true : false;

  return (
    <div className="twoFaContainer">
      <div className="twoFa">
        <h1 className="twoFaLg">Two Step Authentication Discord</h1>
        <h1 className="twoFaSm">
          Enter the 6-digit authentication code generated by your app
        </h1>
        <AuthCode
          onChange={handleOnChange}
          allowedCharacters="numeric"
          containerClassName={"twofaInput"}
        />
        {show2FA && (
          <button className="twofaButton" onClick={CheckTwoFa}>
            Verify 2FA Code
          </button>
        )}
      </div>
      <h1 className="GoLogin2FA" onClick={() => navigate("/login")}>
        Go Back To Login
      </h1>
    </div>
  );
}

export default Verify2FA2;
