# Generated by Django 4.2.11 on 2024-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0004_achievement_achievementperuser_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=255, unique=True),
        ),
    ]
